export interface Organisation {
  id?: string,
  ABN?: string,
  activeStatus?: boolean,
  description?: string,
  img?: string,
  name: string,
  phone: string,
  summary: string,
  website: string,
  file?: FileList,
  totalDonationCount?: number,
  totalDonationItems?: number,
  totalDonations?: number,
  totalDonationsValue?: number,
  totalGeneralDonationsCount?: number,
  totalGeneralDonationsValue?:number,
  totalItemDonationsCount?:number,
  totalItemDonationsValue?:number
}
