import { Timestamp, serverTimestamp } from "firebase/firestore"
import { CreateOrgModel } from "src/app/models/MockDataModels"



export const mockData:CreateOrgModel[] =
  [
    {

        "name": "Barry's Bakehouse",
        "description": "",
        "summary": "Barry's bakehouse provides baked goods and fresh bread daily for local customers. Barry also provides free baked goods to the local nursing home",
        "activeStatus": true,
        "ABN": "27384372612",
        "phone": "0428473288",
        "website": "https://www.barriesbakery.com.au",
        "img": "https://source.unsplash.com/m9pzwmxm2rk",
        "totalDonationCount": 23,
        "totalDonationItems": 4,
        "totalDonationsValue": 2350,
        "totalGeneralDonationsCount": 17,
        "totalGeneralDonationsValue": 1990,
        "totalItemDonationsCount": 6,
        "totalItemDonationsValue": 360,
        "Items":[
          {
            "name": "Mix Master",
            "summary":"This stand mixer has dishwasher safe parts.",
            "description":"It has a white finish. Make a variety of foods and baked goods at home with this Sunbeam stand mixer.",
            "initialPrice": 150,
            "totalDonationCount": 2,
            "totalDonationsValue":142,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/BdiWV88jQFg",
            "itemDonations":[
              {
                "IsRefunded":false,
                "amount":65,
                "comment":"Skid-Steer",
                "donorPublicName":"Vittoria Eccleston",
                "donationDate":serverTimestamp(),
                "private":{
                  "paypalTransactionId":"475730ae-4d4d-448e-b9d8-749fbc5b2fe8",
                  "IsAnon":true,
                  "agreeToContact":true,
                  "email":"tolney0@arstechnica.com",
                  "howHeardOther":"Facebook",
                  "mailingAddress":"3502 Linden Terrace",
                  "name":"Tabbatha Olney",
                  "phoneNumber":"(519) 9540817"
                },
              },

              {
                  "IsRefunded":false,
                  "amount":77,
                  "comment":"Crawler",
                  "donorPublicName":"Kerwinn Hammerstone",
                  "donationDate":serverTimestamp(),
                  "private":{
                    "paypalTransactionId":"6ee85021-bdc0-4d3b-9ccb-d358dca2fb54",
                    "IsAnon":false,
                    "agreeToContact":true,
                    "email":"fcullnean1@cyberchimps.com",
                    "howHeardOther":"Google",
                    "mailingAddress":"8 Mandrake Alley",
                    "name":"Faunie Cullnean",
                    "phoneNumber":"(131) 9243948"
                  },
                },

              {
                  "IsRefunded":true,
                  "amount":38,
                  "comment":"Scraper",
                  "donorPublicName":"Matilda Oxlade",
                  "donationDate":serverTimestamp(),
                  "private":{
                    "paypalTransactionId":"c78c7818-2953-4272-a935-0f713171ec5a",
                    "IsAnon":false,
                    "agreeToContact":true,
                    "email":"sferneyhough2@csmonitor.com",
                    "howHeardOther":"Google",
                    "mailingAddress":"83 Debs Avenue",
                    "name":"Stanislaus Ferneyhough",
                    "phoneNumber":"(150) 8981611"
                  },
                },
            ]
          },
          {
            "name": "Industrial Oven",
            "summary":"The Turbofan E33D5 is a high quality digital electric convection oven with a large 5x 1/1 gastronorm capacity.",
            "description":"Suitable for use in restaurants, canteens, bakeries and others, the Turbofan includes all the features you would expect from a commercial convection oven and is ideal for cooking chicken, pastries, bread, pizza and confectionary. The oven is easily programmable and features a water injection mode when steam or moisture is required in your recipe.",
            "initialPrice": 5000,
            "totalDonationCount": 2,
            "totalDonationsValue":142,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/illedcWylYU",
            "itemDonations":[
              {
                "IsRefunded":false,
                "amount":65,
                "comment":"Skid-Steer",
                "donorPublicName":"Vittoria Eccleston",
                "donationDate":serverTimestamp(),
                "private":{
                  "paypalTransactionId":"bdfdeeb0-b59f-4638-8752-63bf5edf4adb",
                  "IsAnon":true,
                  "agreeToContact":true,
                  "email":"tolney0@arstechnica.com",
                  "howHeardOther":"Facebook",
                  "mailingAddress":"3502 Linden Terrace",
                  "name":"Tabbatha Olney",
                  "phoneNumber":"(519) 9540817"
                },
              },

              {
                  "IsRefunded":false,
                  "amount":77,
                  "comment":"Crawler",
                  "donorPublicName":"Kerwinn Hammerstone",
                  "donationDate":serverTimestamp(),
                  "private":{
                    "paypalTransactionId":"bb372bf1-e5e5-460a-af28-40c05f96b5f6",
                    "IsAnon":false,
                    "agreeToContact":true,
                    "email":"fcullnean1@cyberchimps.com",
                    "howHeardOther":"Google",
                    "mailingAddress":"8 Mandrake Alley",
                    "name":"Faunie Cullnean",
                    "phoneNumber":"(131) 9243948"
                  },
                },

              {
                  "IsRefunded":true,
                  "amount":38,
                  "comment":"Scraper",
                  "donorPublicName":"Matilda Oxlade",
                  "donationDate":serverTimestamp(),
                  "private":{
                    "paypalTransactionId":"517b82f6-9a2c-466b-a570-ae5791c7c996",
                    "IsAnon":false,
                    "agreeToContact":true,
                    "email":"sferneyhough2@csmonitor.com",
                    "howHeardOther":"Google",
                    "mailingAddress":"83 Debs Avenue",
                    "name":"Stanislaus Ferneyhough",
                    "phoneNumber":"(150) 8981611"
                  },
                },
            ]
          },
          {
            "name": "Blender",
            "summary":"Prepare meals, drinks, sauces, soups and more!",
            "description":"Effortlessly whip up delicious smoothies, breakdown coarse grains, dish up tasty hummus and prep food with the 1500W of power, adjustable speed settings and food grade design of the Kogan 1500W Vitablast Blender.",
            "initialPrice": 1000,
            "totalDonationCount": 0,
            "totalDonationsValue":0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/eIqO4P50MeY"
          },
          {
            "name": "15 x Outdoor Chairs",
            "summary":"Materials: teak wood frame, Viro synthetic cord seat, nylon foot pads.",
            "description":"Open weave design, Highly sanded finish, Suitable for indoor or outdoor under cover and Constructed using solid teak wood with woven Viro waterproof cord seat.",
            "initialPrice": 2000,
            "totalDonationCount": 0,
            "totalDonationsValue":0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/fxLTX93WdFg"
          },
        ],
        "GeneralDonations": [
          {
            "IsRefunded": false,
            "amount": 20,
            "comment": "well done I love Trees R us :)",
            "donationDate": serverTimestamp(),
            "donorPublicName": "John",
            "IsSubscribed": false,
            "private": {
              "paypalTransactionId":"451bc1d5-0608-4d39-8f06-d7e419c86ac3",
              "IsAnon": false,
              "agreeToContact": true,
              "email": "example@john.com.au",
              "howHeardOther": "Facebook",
              "mailingAddress": "16 realgood st realville 3136",
              "name": "John Smith",
              "phoneNumber": "0486723474"
          }
        },
          {"IsRefunded":false,
            "amount":184,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Raviv",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1637267745, 0),
            "private":{
                "paypalTransactionId":"e34d647a-ff8e-45fd-8440-f9e6f78abc20",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"ryakuntsov0@huffingtonpost.com",
                "howHeardOther":"Other",
                "mailingAddress":"6512 Killdeer Trail",
                "name":"Roseanna Yakuntsov",
                "phoneNumber":"106-492-8055"
            }
          },
            {"IsRefunded":true,
            "amount":278,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Braden",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1645062608, 0),
            "private":{
                "paypalTransactionId":"26056605-dc9d-40c9-b6e9-c1be1f92f363",
                "IsAnon":true,
                "agreeToContact":true,
                "email":"jberr1@scribd.com",
                "howHeardOther":"Facebook",
                "mailingAddress":"63955 School Alley",
                "name":"Joletta Berr",
                "phoneNumber":"476-335-0517"
            }
},
            {"IsRefunded":false,
            "amount":14,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Duncan",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1660846169, 0),
            "private":{
                "paypalTransactionId":"48fdb357-8468-4786-9fa2-baae9cde7186",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"rhobbert2@icq.com",
                "howHeardOther":"Other",
                "mailingAddress":"36490 Ridgeway Plaza",
                "name":"Rudolf Hobbert",
                "phoneNumber":"984-118-5089"
            }
},
            {"IsRefunded":false,
            "amount":98,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Bryn",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1637791401, 0),
            "private":{
                "paypalTransactionId":"5e1b81d8-5a94-42ac-a542-994c2c3dda25",
                "IsAnon":true,
                "agreeToContact":true,
                "email":"tlissett3@craigslist.org",
                "howHeardOther":"Facebook",
                "mailingAddress":"37 Debra Way",
                "name":"Torey Lissett",
                "phoneNumber":"471-385-5623"
            }
},
            {"IsRefunded":false,
            "amount":41,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Bekki",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1649358315, 0),

            "private":{
                "paypalTransactionId":"2283d757-d385-4d4d-901d-25cdc244b77a",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"mshearstone4@typepad.com",
                "howHeardOther":"Google",
                "mailingAddress":"858 Old Gate Drive",
                "name":"Mitchael Shearstone",
                "phoneNumber":"247-443-8325"
}
},
            {"IsRefunded":false,
            "amount":209,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Winifield",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1635942123, 0),
            "private":{
                "paypalTransactionId":"c05fbed0-b3e9-4eaa-8c0f-c6cf6bd39a6b",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"cbrannigan5@purevolume.com",
                "howHeardOther":"Other",
                "mailingAddress":"89791 Clemons Pass",
                "name":"Cal Brannigan",
                "phoneNumber":"502-396-2041"
            }
},
            {"IsRefunded":true,
            "amount":254,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Pia",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1658131907, 0),
            "private":{
                "paypalTransactionId":"3a9eb1f8-13c0-4565-8bda-94f32196524b",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"rde6@t-online.de",
                "howHeardOther":"Google",
                "mailingAddress":"3257 Crescent Oaks Plaza",
                "name":"Roxane De Cruze",
                "phoneNumber":"671-527-5738"
            }
},
            {"IsRefunded":false,
            "amount":19,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Iolanthe",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1652470903, 0),
            "private":{
                "paypalTransactionId":"d4b85b39-a5ae-4054-8455-d513b93a15d5",
                "IsAnon":true,
                "agreeToContact":true,
                "email":"jerangy7@latimes.com",
                "howHeardOther":"Instagram",
                "mailingAddress":"96480 Northland Trail",
                "name":"Janeen Erangy",
                "phoneNumber":"856-469-6941"
            }
},
            {"IsRefunded":false,
            "amount":211,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Clem",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1646113004, 0),
            "private":{
                "paypalTransactionId":"60b1732e-8069-4bb4-9fc5-78f0268426c6",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"jfasham8@blogs.com",
                "howHeardOther":"Other",
                "mailingAddress":"924 High Crossing Junction",
                "name":"Johanna Fasham",
                "phoneNumber":"158-266-7385"
            }
},
            {"IsRefunded":false,
            "amount":166,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Danice",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1643887865, 0),
            "private":{
                "paypalTransactionId":"c6852715-53ba-49ef-8738-45be8035a246",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"cstollberger9@loc.gov",
                "howHeardOther":"Other",
                "mailingAddress":"66752 Golden Leaf Place",
                "name":"Chrysa Stollberger",
                "phoneNumber":"587-449-9761"
            }
},
            {"IsRefunded":true,
            "amount":263,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Maryanne",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1661510063, 0),
            "private":{
                "paypalTransactionId":"f28a0e2e-90bd-4dec-a0d2-4ddbc4b680ee",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"iperrisa@imageshack.us",
                "howHeardOther":"Instagram",
                "mailingAddress":"18 Dixon Point",
                "name":"Ignatius Perris",
                "phoneNumber":"358-296-8577"
            }
},
            {"IsRefunded":false,
            "amount":92,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Brenna",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1658148094, 0),
            "private":{
                "paypalTransactionId":"6c9e6715-96cf-405c-bcb8-143506fab33b",
                "IsAnon":true,
                "agreeToContact":true,
                "email":"mstockneyb@ftc.gov",
                "howHeardOther":"Other",
                "mailingAddress":"6113 Towne Street",
                "name":"Mateo Stockney",
                "phoneNumber":"491-746-3413"
            }
},
            {"IsRefunded":false,
            "amount":66,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Russell",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1664030463, 0),
            "private":{
                "paypalTransactionId":"1302ba85-9934-466b-9582-530529e1f09e",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"dlittledykec@freewebs.com",
                "howHeardOther":"Other",
                "mailingAddress":"290 Hollow Ridge Court",
                "name":"Darline Littledyke",
                "phoneNumber":"105-346-9535"
            }
},
            {"IsRefunded":true,
            "amount":6,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Elston",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1657953406, 0),
            "private":{
                "paypalTransactionId":"2e10785c-e34c-4901-a90e-2e585462b9ca",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"dlosanod@pinterest.com",
                "howHeardOther":"Instagram",
                "mailingAddress":"92 Victoria Center",
                "name":"Dniren Losano",
                "phoneNumber":"161-792-5330"
            }
},
            {"IsRefunded":true,
            "amount":284,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Antonius",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1660993694, 0),
            "private":{
                "paypalTransactionId":"f303a24b-e035-4487-a1d5-f4189fed927a",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"wmccarneye@simplemachines.org",
                "howHeardOther":"Other",
                "mailingAddress":"10076 Clove Junction",
                "name":"Worthington McCarney",
                "phoneNumber":"242-673-0532"
            }
},
            {"IsRefunded":true,
            "amount":172,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Cam",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1653037483, 0),
            "private":{
                "paypalTransactionId":"3dff9dc9-c6f5-4054-a220-50c2bd026a1e",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"gslatfordf@cnbc.com",
                "howHeardOther":"Other",
                "mailingAddress":"229 Independence Way",
                "name":"Georgette Slatford",
                "phoneNumber":"301-631-0182"
            }
},
            {"IsRefunded":true,
            "amount":127,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Bernie",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1642947603, 0),
            "private":{
                "paypalTransactionId":"27115c81-ac7b-4050-94ae-092505b19d9f",
                "IsAnon":true,
                "agreeToContact":true,
                "email":"geytelg@microsoft.com",
                "howHeardOther":"Facebook",
                "mailingAddress":"3 Kropf Junction",
                "name":"Garrick Eytel",
                "phoneNumber":"401-730-0030"
            }
},
            {"IsRefunded":false,
            "amount":30,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Estrellita",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1662906560, 0),
            "private":{
                "paypalTransactionId":"fc87ebba-88fa-4c58-bcd2-38e1785ad3d8",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"trentilllh@mayoclinic.com",
                "howHeardOther":"Other",
                "mailingAddress":"1 Meadow Ridge Lane",
                "name":"Thorvald Rentilll",
                "phoneNumber":"857-123-2251"
            }
},
            {"IsRefunded":true,
            "amount":131,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Kalila",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1651059211, 0),
            "private":{
                "paypalTransactionId":"434ab266-7f1b-46cd-ab19-287e9a426639",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"tloffilli@opensource.org",
                "howHeardOther":"Other",
                "mailingAddress":"50773 Dwight Trail",
                "name":"Tuckie Loffill",
                "phoneNumber":"818-542-9125"
            }
},
            {"IsRefunded":false,
            "amount":29,
            "comment":"Wow Great Paypal Experience love it",
            "donorPublicName":"Terza",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1650551611, 0),
            "private":{
                "paypalTransactionId":"8469c2d0-9eb9-48c3-a9c7-f79d7297da27",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"mcrossthwaitej@xing.com",
                "howHeardOther":"Facebook",
                "mailingAddress":"24009 Sutherland Park",
                "name":"Michal Crossthwaite",
                "phoneNumber":"274-938-9868"
            }
},
            {"IsRefunded":true,
            "amount":250,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Justina",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1658014983, 0),
            "private":{
                "paypalTransactionId":"d8c24aba-aa1b-4faf-a522-47805a26b088",
                "IsAnon":false,
                "agreeToContact":true,
                "email":"espilsburiek@statcounter.com",
                "howHeardOther":"Other",
                "mailingAddress":"10847 Talisman Street",
                "name":"Emlynne Spilsburie",
                "phoneNumber":"176-855-2778"
            }
},
            {"IsRefunded":true,
            "amount":258,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Nadya",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1650420277, 0),
            "private":{
                "paypalTransactionId":"ba822f6d-4a9e-4635-86ca-d6a7d5930eee",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"gantleyl@noaa.gov",
                "howHeardOther":"Other",
                "mailingAddress":"36 Lunder Place",
                "name":"Guillaume Antley",
                "phoneNumber":"348-657-0056"
            }
},
            {"IsRefunded":false,
            "amount":277,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Ingeberg",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1658283384, 0),
            "private":{
                "paypalTransactionId":"8c8a9a3d-b626-425d-bfc5-9a282067833f",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"gdilstonm@narod.ru",
                "howHeardOther":"Other",
                "mailingAddress":"00 Dennis Road",
                "name":"Griffin Dilston",
                "phoneNumber":"616-803-6348"
            }
},
            {"IsRefunded":true,
            "amount":21,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Nada",
            "IsSubscribed":false,
            "donationDate":new Timestamp(1650223169, 0),
            "private":{
                "paypalTransactionId":"be47d2b0-4a10-4cf3-bdfd-6c5b817fab9e",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"ckincaden@about.com",
                "howHeardOther":"Other",
                "mailingAddress":"0272 Brentwood Circle",
                "name":"Charyl Kincade",
                "phoneNumber":"313-561-1994"
            }
},
            {"IsRefunded":true,
            "amount":55,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Gage",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1647762205, 0),
            "private":{
                "paypalTransactionId":"2c18dc35-c609-411a-8cd7-bd3a4a3f2017",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"dmarono@ucoz.com",
                "howHeardOther":"Other",
                "mailingAddress":"45 Dayton Way",
                "name":"Deane Maron",
                "phoneNumber":"240-606-2747"
            }
},
            {"IsRefunded":true,
            "amount":140,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Roxi",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1654854912, 0),
            "private":{
                "paypalTransactionId":"e44482d0-12e0-45f2-b5bc-b3827ce08073",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"mlonerganp@booking.com",
                "howHeardOther":"Other",
                "mailingAddress":"6 Milwaukee Junction",
                "name":"Martica Lonergan",
                "phoneNumber":"251-286-7225"
            }
},
            {"IsRefunded":false,
            "amount":91,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Kania",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1647248215, 0),
            "private":{
                "paypalTransactionId":"82ec3f1d-02dd-4c69-92be-55e46a068eb3",
                "IsAnon":true,
                "agreeToContact":true,
                "email":"eescalanteq@va.gov",
                "howHeardOther":"Instagram",
                "mailingAddress":"5029 Gerald Lane",
                "name":"Errol Escalante",
                "phoneNumber":"347-286-7238"
            }
},
            {"IsRefunded":false,
            "amount":275,
            "comment":"This is the best experience I have ever had in my life",
            "donorPublicName":"Anetta",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1636594714, 0),
            "private":{
                "paypalTransactionId":"d6e27312-4019-4646-a8bb-199abc6c44f8",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"bjensonr@jigsy.com",
                "howHeardOther":"Other",
                "mailingAddress":"0083 Parkside Alley",
                "name":"Blanca Jenson",
                "phoneNumber":"589-975-8928"
            }
},
            {"IsRefunded":false,
            "amount":168,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Putnam",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1634393719, 0),
            "private":{
                "paypalTransactionId":"a7e140ea-6352-4a38-9e2f-ba5507573544",
                "IsAnon":false,
                "agreeToContact":false,
                "email":"lmcclarens@constantcontact.com",
                "howHeardOther":"Instagram",
                "mailingAddress":"1177 Eliot Drive",
                "name":"Lory McClaren",
                "phoneNumber":"695-917-3964"
            }
},
            {"IsRefunded":true,
            "amount":189,
            "comment":"Highly Reccomend this product",
            "donorPublicName":"Augustin",
            "IsSubscribed":true,
            "donationDate":new Timestamp(1640462811, 0),
            "private":{
                "paypalTransactionId":"a55a7f20-4ac0-4333-831b-ff309002bcbb",
                "IsAnon":true,
                "agreeToContact":false,
                "email":"pizhakt@ucla.edu",
                "howHeardOther":"Other",
                "mailingAddress":"511 Shasta Hill",
                "name":"Pavel Izhak",
                "phoneNumber":"623-605-3944"
            }
          },
        ]
    },
    {

        "name": "The Phone Zone",
        "description": "",
        "summary": "The phone zone is a business providing phone repairs and sales.",
        "activeStatus": false,
        "ABN": "49382719557",
        "phone": "0455567982",
        "website": "https://www.phonezone.com",
        "img": "https://source.unsplash.com/6wdRuK7bVTE",
        "totalDonationCount": 0,
        "totalDonationItems": 3,
        "totalDonationsValue": 0,
        "totalGeneralDonationsCount": 0,
        "totalGeneralDonationsValue": 0,
        "totalItemDonationsCount": 0,
        "totalItemDonationsValue": 0,
        "Items":[
          {
            "name": "IPhone X",
            "summary":"Excellent smartphone",
            "description":"Unmatched design and build",
            "initialPrice": 350,
            "totalDonationCount": 0,
            "totalDonationsValue":0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/OxvlDO8RwKg"
          },
          {
            "name": "Phone Screen Replacement",
            "summary":"Brand new phone screen",
            "description":"Service for replacing a broken phone screen",
            "initialPrice": 58,
            "totalDonationCount": 0,
            "totalDonationsValue": 0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/6XBEYe3G_08"
          },
          {
            "name": "Screen protection",
            "summary":"Protects your phone from scratches and chips",
            "description":"Add a screen protector to your phone",
            "initialPrice": 20,
            "totalDonationCount": 0,
            "totalDonationsValue": 0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/dQcj0H8BcmU"
          },


        ],
//         "GeneralDonations": [
//           {
//             "IsRefunded": false,
//             "amount": 20,
//             "comment": "well done I love Trees R us :)",
//             "donationDate": serverTimestamp(),
//             "donorPublicName": "John",
//             "IsSubscribed": false,
//             "private": {
//               "paypalTransactionId":"18e1edac-51be-4117-bc78-9988d3a42c5b",
//               "IsAnon": false,
//               "agreeToContact": true,
//               "email": "example@john.com.au",
//               "howHeardOther": "Facebook",
//               "mailingAddress": "16 realgood st realville 3136",
//               "name": "John Smith",
//               "phoneNumber": "0486723474"
//           }
//         },
//           {"IsRefunded":false,
//             "amount":184,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Raviv",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1637267745, 0),
//             "private":{
//                 "paypalTransactionId":"d5906a8d-206c-49cb-9d94-824a4780bd31",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"ryakuntsov0@huffingtonpost.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"6512 Killdeer Trail",
//                 "name":"Roseanna Yakuntsov",
//                 "phoneNumber":"106-492-8055"
//             }
//           },
//             {"IsRefunded":true,
//             "amount":278,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Braden",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1645062608, 0),
//             "private":{
//                 "paypalTransactionId":"e78d3acf-a8a5-4136-9ef7-df744e2fe244",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"jberr1@scribd.com",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"63955 School Alley",
//                 "name":"Joletta Berr",
//                 "phoneNumber":"476-335-0517"
//             }
// },
//             {"IsRefunded":false,
//             "amount":14,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Duncan",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1660846169, 0),
//             "private":{
//                 "paypalTransactionId":"8bc3c28c-88a7-4e51-ad63-be57fd2eaa92",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"rhobbert2@icq.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"36490 Ridgeway Plaza",
//                 "name":"Rudolf Hobbert",
//                 "phoneNumber":"984-118-5089"
//             }
// },
//             {"IsRefunded":false,
//             "amount":98,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Bryn",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1637791401, 0),
//             "private":{
//                 "paypalTransactionId":"749e2c85-3eb0-4e46-9745-75687eb4ff91",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"tlissett3@craigslist.org",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"37 Debra Way",
//                 "name":"Torey Lissett",
//                 "phoneNumber":"471-385-5623"
//             }
// },
//             {"IsRefunded":false,
//             "amount":41,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Bekki",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1649358315, 0),

//             "private":{
//                 "paypalTransactionId":"a000d40f-e72b-415b-b18a-de5c52bcc0ff",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"mshearstone4@typepad.com",
//                 "howHeardOther":"Google",
//                 "mailingAddress":"858 Old Gate Drive",
//                 "name":"Mitchael Shearstone",
//                 "phoneNumber":"247-443-8325"
// }
// },
//             {"IsRefunded":false,
//             "amount":209,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Winifield",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1635942123, 0),
//             "private":{
//                 "paypalTransactionId":"2784e533-cad8-4940-8e08-72532f8f6e11",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"cbrannigan5@purevolume.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"89791 Clemons Pass",
//                 "name":"Cal Brannigan",
//                 "phoneNumber":"502-396-2041"
//             }
// },
//             {"IsRefunded":true,
//             "amount":254,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Pia",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1658131907, 0),
//             "private":{
//                 "paypalTransactionId":"568b5cdc-a268-4f7d-8913-296e6ba858dd",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"rde6@t-online.de",
//                 "howHeardOther":"Google",
//                 "mailingAddress":"3257 Crescent Oaks Plaza",
//                 "name":"Roxane De Cruze",
//                 "phoneNumber":"671-527-5738"
//             }
// },
//             {"IsRefunded":false,
//             "amount":19,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Iolanthe",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1652470903, 0),
//             "private":{
//                 "paypalTransactionId":"12c9cb47-5c85-40ca-8002-b1f01c67bcb4",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"jerangy7@latimes.com",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"96480 Northland Trail",
//                 "name":"Janeen Erangy",
//                 "phoneNumber":"856-469-6941"
//             }
// },
//             {"IsRefunded":false,
//             "amount":211,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Clem",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1646113004, 0),
//             "private":{
//                 "paypalTransactionId":"459f6ae3-9267-4248-8a3f-609a5070674c",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"jfasham8@blogs.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"924 High Crossing Junction",
//                 "name":"Johanna Fasham",
//                 "phoneNumber":"158-266-7385"
//             }
// },
//             {"IsRefunded":false,
//             "amount":166,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Danice",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1643887865, 0),
//             "private":{
//                 "paypalTransactionId":"54a1b211-c5c1-4af8-89d3-43f9cfc8cfb1",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"cstollberger9@loc.gov",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"66752 Golden Leaf Place",
//                 "name":"Chrysa Stollberger",
//                 "phoneNumber":"587-449-9761"
//             }
// },
//             {"IsRefunded":true,
//             "amount":263,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Maryanne",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1661510063, 0),
//             "private":{
//                 "paypalTransactionId":"24c934bd-9084-4980-908c-77231062279f",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"iperrisa@imageshack.us",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"18 Dixon Point",
//                 "name":"Ignatius Perris",
//                 "phoneNumber":"358-296-8577"
//             }
// },
//             {"IsRefunded":false,
//             "amount":92,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Brenna",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1658148094, 0),
//             "private":{
//                 "paypalTransactionId":"63b9e918-bcae-4cb7-afce-8c773e6aa77b",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"mstockneyb@ftc.gov",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"6113 Towne Street",
//                 "name":"Mateo Stockney",
//                 "phoneNumber":"491-746-3413"
//             }
// },
//             {"IsRefunded":false,
//             "amount":66,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Russell",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1664030463, 0),
//             "private":{
//                 "paypalTransactionId":"5f6c8f1e-c257-4da7-bcc8-1726164dfdea",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"dlittledykec@freewebs.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"290 Hollow Ridge Court",
//                 "name":"Darline Littledyke",
//                 "phoneNumber":"105-346-9535"
//             }
// },
//             {"IsRefunded":true,
//             "amount":6,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Elston",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1657953406, 0),
//             "private":{
//                 "paypalTransactionId":"be1a8be9-8811-41e9-b263-f4aea41de199",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"dlosanod@pinterest.com",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"92 Victoria Center",
//                 "name":"Dniren Losano",
//                 "phoneNumber":"161-792-5330"
//             }
// },
//             {"IsRefunded":true,
//             "amount":284,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Antonius",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1660993694, 0),
//             "private":{
//                 "paypalTransactionId":"42be5643-ecd2-4731-921b-000eb0e3c84e",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"wmccarneye@simplemachines.org",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"10076 Clove Junction",
//                 "name":"Worthington McCarney",
//                 "phoneNumber":"242-673-0532"
//             }
// },
//             {"IsRefunded":true,
//             "amount":172,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Cam",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1653037483, 0),
//             "private":{
//                 "paypalTransactionId":"95881189-9f83-4279-a65e-79001d239525",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"gslatfordf@cnbc.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"229 Independence Way",
//                 "name":"Georgette Slatford",
//                 "phoneNumber":"301-631-0182"
//             }
// },
//             {"IsRefunded":true,
//             "amount":127,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Bernie",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1642947603, 0),
//             "private":{
//                 "paypalTransactionId":"9c59dc4d-70d9-4b68-8151-9342a65ff476",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"geytelg@microsoft.com",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"3 Kropf Junction",
//                 "name":"Garrick Eytel",
//                 "phoneNumber":"401-730-0030"
//             }
// },
//             {"IsRefunded":false,
//             "amount":30,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Estrellita",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1662906560, 0),
//             "private":{
//                 "paypalTransactionId":"bc9ada9f-59bf-4e60-8726-25ff9ccc6362",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"trentilllh@mayoclinic.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"1 Meadow Ridge Lane",
//                 "name":"Thorvald Rentilll",
//                 "phoneNumber":"857-123-2251"
//             }
// },
//             {"IsRefunded":true,
//             "amount":131,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Kalila",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1651059211, 0),
//             "private":{
//                 "paypalTransactionId":"68a3d6c9-822e-46ed-9694-7e8ed2008707",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"tloffilli@opensource.org",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"50773 Dwight Trail",
//                 "name":"Tuckie Loffill",
//                 "phoneNumber":"818-542-9125"
//             }
// },
//             {"IsRefunded":false,
//             "amount":29,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Terza",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1650551611, 0),
//             "private":{
//                 "paypalTransactionId":"5ae26a84-9f6a-475d-924b-8ec706f6fbff",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"mcrossthwaitej@xing.com",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"24009 Sutherland Park",
//                 "name":"Michal Crossthwaite",
//                 "phoneNumber":"274-938-9868"
//             }
// },
//             {"IsRefunded":true,
//             "amount":250,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Justina",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1658014983, 0),
//             "private":{
//                 "paypalTransactionId":"5a967e3c-78ce-4954-8199-bb0f6d56c533",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"espilsburiek@statcounter.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"10847 Talisman Street",
//                 "name":"Emlynne Spilsburie",
//                 "phoneNumber":"176-855-2778"
//             }
// },
//             {"IsRefunded":true,
//             "amount":258,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Nadya",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1650420277, 0),
//             "private":{
//                 "paypalTransactionId":"217d3aab-48fe-4bc6-a65b-987f7865aa72",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"gantleyl@noaa.gov",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"36 Lunder Place",
//                 "name":"Guillaume Antley",
//                 "phoneNumber":"348-657-0056"
//             }
// },
//             {"IsRefunded":false,
//             "amount":277,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Ingeberg",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1658283384, 0),
//             "private":{
//                 "paypalTransactionId":"279b7442-96ab-439c-abfa-67f91e2374f8",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"gdilstonm@narod.ru",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"00 Dennis Road",
//                 "name":"Griffin Dilston",
//                 "phoneNumber":"616-803-6348"
//             }
// },
//             {"IsRefunded":true,
//             "amount":21,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Nada",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1650223169, 0),
//             "private":{
//                 "paypalTransactionId":"e2c54f06-1a0e-4572-b3f1-a67d2c0ca079",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"ckincaden@about.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"0272 Brentwood Circle",
//                 "name":"Charyl Kincade",
//                 "phoneNumber":"313-561-1994"
//             }
// },
//             {"IsRefunded":true,
//             "amount":55,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Gage",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1647762205, 0),
//             "private":{
//                 "paypalTransactionId":"e90d19c1-861e-4515-a208-c366895145c0",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"dmarono@ucoz.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"45 Dayton Way",
//                 "name":"Deane Maron",
//                 "phoneNumber":"240-606-2747"
//             }
// },
//             {"IsRefunded":true,
//             "amount":140,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Roxi",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1654854912, 0),
//             "private":{
//                 "paypalTransactionId":"32b40e52-c4bf-466e-8449-2925da4fc9f1",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"mlonerganp@booking.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"6 Milwaukee Junction",
//                 "name":"Martica Lonergan",
//                 "phoneNumber":"251-286-7225"
//             }
// },
//             {"IsRefunded":false,
//             "amount":91,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Kania",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1647248215, 0),
//             "private":{
//                 "paypalTransactionId":"6d727a72-1bb1-4bda-a7db-7b4cde81d170",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"eescalanteq@va.gov",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"5029 Gerald Lane",
//                 "name":"Errol Escalante",
//                 "phoneNumber":"347-286-7238"
//             }
// },
//             {"IsRefunded":false,
//             "amount":275,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Anetta",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1636594714, 0),
//             "private":{
//                 "paypalTransactionId":"ca8b5211-2eb6-4861-bd66-4ff6015fd72d",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"bjensonr@jigsy.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"0083 Parkside Alley",
//                 "name":"Blanca Jenson",
//                 "phoneNumber":"589-975-8928"
//             }
// },
//             {"IsRefunded":false,
//             "amount":168,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Putnam",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1634393719, 0),
//             "private":{
//                 "paypalTransactionId":"2051041a-cece-46b4-a1c3-ebefb01340a1",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"lmcclarens@constantcontact.com",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"1177 Eliot Drive",
//                 "name":"Lory McClaren",
//                 "phoneNumber":"695-917-3964"
//             }
// },
//             {"IsRefunded":true,
//             "amount":189,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Augustin",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1640462811, 0),
//             "private":{
//                 "paypalTransactionId":"977508b5-81f7-48fe-a410-204f1ce33fa1",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"pizhakt@ucla.edu",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"511 Shasta Hill",
//                 "name":"Pavel Izhak",
//                 "phoneNumber":"623-605-3944"
//             }
//           },
//         ]

    },
    {

        "name": "Social Moments",
        "description": "",
        "summary": "Provides yummy social treats",
        "activeStatus": true,
        "ABN": "22999684773",
        "phone": "0433958444",
        "website": "https://social-moments.org/",
        "img": "https://source.unsplash.com/Zyx1bK9mqmA",
        "totalDonationCount": 0,
        "totalDonationItems": 3,
        "totalDonationsValue": 0,
        "totalGeneralDonationsCount": 0,
        "totalGeneralDonationsValue": 0,
        "totalItemDonationsCount": 0,
        "totalItemDonationsValue": 0,
        "Items":[
          {
            "name": "SoCrunchees",
            "summary":"Crunchy & Chewy",
            "description":"Anzacz with a crunchy and chewy twitst",
            "initialPrice": 30,
            "totalDonationCount": 0,
            "totalDonationsValue":0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/-FyA5fhIPGI"
          },
          {
            "name": "SoTweetees",
            "summary":"Gluten Free",
            "description":"You'll be top of the pecking order with these delicious seed bars.",
            "initialPrice": 72,
            "totalDonationCount": 0,
            "totalDonationsValue":0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/iiQZcCtfpyk"
          },
          {
            "name": "SoChunky",
            "summary":"Seriously Chunky",
            "description":"New York hits Melbourne.  Sweet and crunchy. Choc chip, nut decadence.",
            "initialPrice": 99,
            "totalDonationCount": 0,
            "totalDonationsValue":0,
            "activeStatus": true,
            "dateCompleted":null,
            "createdAt": serverTimestamp(),
            "img": "https://source.unsplash.com/rjf4FcmERGc"
          },
        ],
//         "GeneralDonations": [
//           {
//             "IsRefunded": false,
//             "amount": 20,
//             "comment": "well done I love Trees R us :)",
//             "donationDate": serverTimestamp(),
//             "donorPublicName": "John",
//             "IsSubscribed": false,
//             "private": {
//               "paypalTransactionId":"bd974790-f339-4602-876e-eeaec86eb635",
//               "IsAnon": false,
//               "agreeToContact": true,
//               "email": "example@john.com.au",
//               "howHeardOther": "Facebook",
//               "mailingAddress": "16 realgood st realville 3136",
//               "name": "John Smith",
//               "phoneNumber": "0486723474"
//           }
//         },
//           {"IsRefunded":false,
//             "amount":184,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Raviv",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1637267745, 0),
//             "private":{
//                 "paypalTransactionId":"224850ce-8fe0-4c30-a35d-2a1e1df45af7",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"ryakuntsov0@huffingtonpost.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"6512 Killdeer Trail",
//                 "name":"Roseanna Yakuntsov",
//                 "phoneNumber":"106-492-8055"
//             }
//           },
//             {"IsRefunded":true,
//             "amount":278,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Braden",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1645062608, 0),
//             "private":{
//                 "paypalTransactionId":"388a5316-df15-4eec-bf30-d097075e51ec",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"jberr1@scribd.com",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"63955 School Alley",
//                 "name":"Joletta Berr",
//                 "phoneNumber":"476-335-0517"
//             }
// },
//             {"IsRefunded":false,
//             "amount":14,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Duncan",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1660846169, 0),
//             "private":{
//                 "paypalTransactionId":"62c8c57c-1d22-42a9-8ebe-563f05347f1c",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"rhobbert2@icq.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"36490 Ridgeway Plaza",
//                 "name":"Rudolf Hobbert",
//                 "phoneNumber":"984-118-5089"
//             }
// },
//             {"IsRefunded":false,
//             "amount":98,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Bryn",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1637791401, 0),
//             "private":{
//                 "paypalTransactionId":"2027608e-541a-4112-8853-96d4b0d41996",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"tlissett3@craigslist.org",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"37 Debra Way",
//                 "name":"Torey Lissett",
//                 "phoneNumber":"471-385-5623"
//             }
// },
//             {"IsRefunded":false,
//             "amount":41,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Bekki",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1649358315, 0),

//             "private":{
//                 "paypalTransactionId":"c9691ef0-71a5-4710-a1b7-4fcb49e1d42e",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"mshearstone4@typepad.com",
//                 "howHeardOther":"Google",
//                 "mailingAddress":"858 Old Gate Drive",
//                 "name":"Mitchael Shearstone",
//                 "phoneNumber":"247-443-8325"
// }
// },
//             {"IsRefunded":false,
//             "amount":209,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Winifield",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1635942123, 0),
//             "private":{
//                 "paypalTransactionId":"a4cad956-882f-48ef-84f8-d6b287a3f7e6",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"cbrannigan5@purevolume.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"89791 Clemons Pass",
//                 "name":"Cal Brannigan",
//                 "phoneNumber":"502-396-2041"
//             }
// },
//             {"IsRefunded":true,
//             "amount":254,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Pia",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1658131907, 0),
//             "private":{
//                 "paypalTransactionId":"eb2f08b6-5811-4408-bf37-636f7d486c64",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"rde6@t-online.de",
//                 "howHeardOther":"Google",
//                 "mailingAddress":"3257 Crescent Oaks Plaza",
//                 "name":"Roxane De Cruze",
//                 "phoneNumber":"671-527-5738"
//             }
// },
//             {"IsRefunded":false,
//             "amount":19,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Iolanthe",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1652470903, 0),
//             "private":{
//                 "paypalTransactionId":"b0a1f9de-63f0-4e1b-9b12-6dd022770a93",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"jerangy7@latimes.com",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"96480 Northland Trail",
//                 "name":"Janeen Erangy",
//                 "phoneNumber":"856-469-6941"
//             }
// },
//             {"IsRefunded":false,
//             "amount":211,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Clem",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1646113004, 0),
//             "private":{
//                 "paypalTransactionId":"7f7fbefa-65f9-48c1-ac04-0120bc6ba7cd",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"jfasham8@blogs.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"924 High Crossing Junction",
//                 "name":"Johanna Fasham",
//                 "phoneNumber":"158-266-7385"
//             }
// },
//             {"IsRefunded":false,
//             "amount":166,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Danice",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1643887865, 0),
//             "private":{
//                 "paypalTransactionId":"8d4694ea-d4c4-46d0-97a6-e03deb966b4b",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"cstollberger9@loc.gov",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"66752 Golden Leaf Place",
//                 "name":"Chrysa Stollberger",
//                 "phoneNumber":"587-449-9761"
//             }
// },
//             {"IsRefunded":true,
//             "amount":263,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Maryanne",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1661510063, 0),
//             "private":{
//                 "paypalTransactionId":"6760f45a-6f44-4c24-aea6-872ef08e1ce1",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"iperrisa@imageshack.us",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"18 Dixon Point",
//                 "name":"Ignatius Perris",
//                 "phoneNumber":"358-296-8577"
//             }
// },
//             {"IsRefunded":false,
//             "amount":92,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Brenna",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1658148094, 0),
//             "private":{
//                 "paypalTransactionId":"fd39c006-e97a-45dc-9749-abe9e0c12d93",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"mstockneyb@ftc.gov",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"6113 Towne Street",
//                 "name":"Mateo Stockney",
//                 "phoneNumber":"491-746-3413"
//             }
// },
//             {"IsRefunded":false,
//             "amount":66,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Russell",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1664030463, 0),
//             "private":{
//                 "paypalTransactionId":"df9c3336-8946-4f6e-b686-7ad7dfb4cfa4",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"dlittledykec@freewebs.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"290 Hollow Ridge Court",
//                 "name":"Darline Littledyke",
//                 "phoneNumber":"105-346-9535"
//             }
// },
//             {"IsRefunded":true,
//             "amount":6,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Elston",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1657953406, 0),
//             "private":{
//                 "paypalTransactionId":"0cca6ae5-3163-41a6-b569-010f66214aa6",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"dlosanod@pinterest.com",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"92 Victoria Center",
//                 "name":"Dniren Losano",
//                 "phoneNumber":"161-792-5330"
//             }
// },
//             {"IsRefunded":true,
//             "amount":284,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Antonius",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1660993694, 0),
//             "private":{
//                 "paypalTransactionId":"30f63211-776b-4581-b73d-898abb54237f",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"wmccarneye@simplemachines.org",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"10076 Clove Junction",
//                 "name":"Worthington McCarney",
//                 "phoneNumber":"242-673-0532"
//             }
// },
//             {"IsRefunded":true,
//             "amount":172,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Cam",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1653037483, 0),
//             "private":{
//                 "paypalTransactionId":"29b01d0b-5eef-498d-956f-40db8a3d85cf",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"gslatfordf@cnbc.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"229 Independence Way",
//                 "name":"Georgette Slatford",
//                 "phoneNumber":"301-631-0182"
//             }
// },
//             {"IsRefunded":true,
//             "amount":127,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Bernie",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1642947603, 0),
//             "private":{
//                 "paypalTransactionId":"656c1fbb-bffb-4e59-bacf-11f6a1564fd6",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"geytelg@microsoft.com",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"3 Kropf Junction",
//                 "name":"Garrick Eytel",
//                 "phoneNumber":"401-730-0030"
//             }
// },
//             {"IsRefunded":false,
//             "amount":30,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Estrellita",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1662906560, 0),
//             "private":{
//                 "paypalTransactionId":"8c0f1952-9dcb-46f0-8217-c9877b2fa8fd",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"trentilllh@mayoclinic.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"1 Meadow Ridge Lane",
//                 "name":"Thorvald Rentilll",
//                 "phoneNumber":"857-123-2251"
//             }
// },
//             {"IsRefunded":true,
//             "amount":131,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Kalila",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1651059211, 0),
//             "private":{
//                 "paypalTransactionId":"d6bd4e51-8c38-481b-8bd4-99bcb0feb6a6",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"tloffilli@opensource.org",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"50773 Dwight Trail",
//                 "name":"Tuckie Loffill",
//                 "phoneNumber":"818-542-9125"
//             }
// },
//             {"IsRefunded":false,
//             "amount":29,
//             "comment":"Wow Great Paypal Experience love it",
//             "donorPublicName":"Terza",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1650551611, 0),
//             "private":{
//                 "paypalTransactionId":"03835e82-bcde-4444-b7a8-26c03a8a5509",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"mcrossthwaitej@xing.com",
//                 "howHeardOther":"Facebook",
//                 "mailingAddress":"24009 Sutherland Park",
//                 "name":"Michal Crossthwaite",
//                 "phoneNumber":"274-938-9868"
//             }
// },
//             {"IsRefunded":true,
//             "amount":250,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Justina",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1658014983, 0),
//             "private":{
//                 "paypalTransactionId":"591157d8-3018-42d5-ab8e-f15cc3db1620",
//                 "IsAnon":false,
//                 "agreeToContact":true,
//                 "email":"espilsburiek@statcounter.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"10847 Talisman Street",
//                 "name":"Emlynne Spilsburie",
//                 "phoneNumber":"176-855-2778"
//             }
// },
//             {"IsRefunded":true,
//             "amount":258,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Nadya",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1650420277, 0),
//             "private":{
//                 "paypalTransactionId":"1f46c188-7d4f-4803-bad5-0f9276edf57c",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"gantleyl@noaa.gov",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"36 Lunder Place",
//                 "name":"Guillaume Antley",
//                 "phoneNumber":"348-657-0056"
//             }
// },
//             {"IsRefunded":false,
//             "amount":277,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Ingeberg",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1658283384, 0),
//             "private":{
//                 "paypalTransactionId":"a1e34d36-8e2e-4c5c-9a8d-fe21af55f5d8",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"gdilstonm@narod.ru",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"00 Dennis Road",
//                 "name":"Griffin Dilston",
//                 "phoneNumber":"616-803-6348"
//             }
// },
//             {"IsRefunded":true,
//             "amount":21,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Nada",
//             "IsSubscribed":false,
//             "donationDate":new Timestamp(1650223169, 0),
//             "private":{
//                 "paypalTransactionId":"9d434590-43e1-46ee-a2c5-25276620a450",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"ckincaden@about.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"0272 Brentwood Circle",
//                 "name":"Charyl Kincade",
//                 "phoneNumber":"313-561-1994"
//             }
// },
//             {"IsRefunded":true,
//             "amount":55,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Gage",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1647762205, 0),
//             "private":{
//                 "paypalTransactionId":"218467e1-ff25-4ced-a4e4-9d702307a85c",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"dmarono@ucoz.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"45 Dayton Way",
//                 "name":"Deane Maron",
//                 "phoneNumber":"240-606-2747"
//             }
// },
//             {"IsRefunded":true,
//             "amount":140,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Roxi",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1654854912, 0),
//             "private":{
//                 "paypalTransactionId":"4e63d041-ed87-47e7-ba36-83095c47896e",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"mlonerganp@booking.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"6 Milwaukee Junction",
//                 "name":"Martica Lonergan",
//                 "phoneNumber":"251-286-7225"
//             }
// },
//             {"IsRefunded":false,
//             "amount":91,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Kania",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1647248215, 0),
//             "private":{
//                 "paypalTransactionId":"94652b68-48b4-4a5d-9203-a041aea4a1a3",
//                 "IsAnon":true,
//                 "agreeToContact":true,
//                 "email":"eescalanteq@va.gov",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"5029 Gerald Lane",
//                 "name":"Errol Escalante",
//                 "phoneNumber":"347-286-7238"
//             }
// },
//             {"IsRefunded":false,
//             "amount":275,
//             "comment":"This is the best experience I have ever had in my life",
//             "donorPublicName":"Anetta",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1636594714, 0),
//             "private":{
//                 "paypalTransactionId":"b6b5e1ae-01fe-446b-a800-5ba9ea995851",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"bjensonr@jigsy.com",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"0083 Parkside Alley",
//                 "name":"Blanca Jenson",
//                 "phoneNumber":"589-975-8928"
//             }
// },
//             {"IsRefunded":false,
//             "amount":168,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Putnam",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1634393719, 0),
//             "private":{
//                 "paypalTransactionId":"a4fcf2e1-060d-4bb9-8c01-2683cc8b71ab",
//                 "IsAnon":false,
//                 "agreeToContact":false,
//                 "email":"lmcclarens@constantcontact.com",
//                 "howHeardOther":"Instagram",
//                 "mailingAddress":"1177 Eliot Drive",
//                 "name":"Lory McClaren",
//                 "phoneNumber":"695-917-3964"
//             }
// },
//             {"IsRefunded":true,
//             "amount":189,
//             "comment":"Highly Reccomend this product",
//             "donorPublicName":"Augustin",
//             "IsSubscribed":true,
//             "donationDate":new Timestamp(1640462811, 0),
//             "private":{
//                 "paypalTransactionId":"63b1220c-4f98-42d1-98c9-50b561b01a7c",
//                 "IsAnon":true,
//                 "agreeToContact":false,
//                 "email":"pizhakt@ucla.edu",
//                 "howHeardOther":"Other",
//                 "mailingAddress":"511 Shasta Hill",
//                 "name":"Pavel Izhak",
//                 "phoneNumber":"623-605-3944"
//             }
//           },
//         ]
    }
  ]
